// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interface.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/interface.go -destination=internal/repository/mocks/interface.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "orderfoodonline/internal/repository/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProductRepository is a mock of ProductRepository interface.
type MockProductRepository struct {
	ctrl     *gomock.Controller
	recorder *MockProductRepositoryMockRecorder
	isgomock struct{}
}

// MockProductRepositoryMockRecorder is the mock recorder for MockProductRepository.
type MockProductRepositoryMockRecorder struct {
	mock *MockProductRepository
}

// NewMockProductRepository creates a new mock instance.
func NewMockProductRepository(ctrl *gomock.Controller) *MockProductRepository {
	mock := &MockProductRepository{ctrl: ctrl}
	mock.recorder = &MockProductRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductRepository) EXPECT() *MockProductRepositoryMockRecorder {
	return m.recorder
}

// BulkInsertProducts mocks base method.
func (m *MockProductRepository) BulkInsertProducts(ctx context.Context, products []models.Product) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkInsertProducts", ctx, products)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkInsertProducts indicates an expected call of BulkInsertProducts.
func (mr *MockProductRepositoryMockRecorder) BulkInsertProducts(ctx, products any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkInsertProducts", reflect.TypeOf((*MockProductRepository)(nil).BulkInsertProducts), ctx, products)
}

// FindProductByID mocks base method.
func (m *MockProductRepository) FindProductByID(ctx context.Context, id string) (*models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindProductByID", ctx, id)
	ret0, _ := ret[0].(*models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindProductByID indicates an expected call of FindProductByID.
func (mr *MockProductRepositoryMockRecorder) FindProductByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindProductByID", reflect.TypeOf((*MockProductRepository)(nil).FindProductByID), ctx, id)
}

// GetAppliedMigrations mocks base method.
func (m *MockProductRepository) GetAppliedMigrations(ctx context.Context) ([]models.Migration, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppliedMigrations", ctx)
	ret0, _ := ret[0].([]models.Migration)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAppliedMigrations indicates an expected call of GetAppliedMigrations.
func (mr *MockProductRepositoryMockRecorder) GetAppliedMigrations(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppliedMigrations", reflect.TypeOf((*MockProductRepository)(nil).GetAppliedMigrations), ctx)
}

// InsertMigration mocks base method.
func (m *MockProductRepository) InsertMigration(ctx context.Context, migration *models.Migration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertMigration", ctx, migration)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertMigration indicates an expected call of InsertMigration.
func (mr *MockProductRepositoryMockRecorder) InsertMigration(ctx, migration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertMigration", reflect.TypeOf((*MockProductRepository)(nil).InsertMigration), ctx, migration)
}

// ListProducts mocks base method.
func (m *MockProductRepository) ListProducts(ctx context.Context) ([]models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", ctx)
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockProductRepositoryMockRecorder) ListProducts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockProductRepository)(nil).ListProducts), ctx)
}

// UpdateMigration mocks base method.
func (m *MockProductRepository) UpdateMigration(ctx context.Context, migration *models.Migration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMigration", ctx, migration)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMigration indicates an expected call of UpdateMigration.
func (mr *MockProductRepositoryMockRecorder) UpdateMigration(ctx, migration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMigration", reflect.TypeOf((*MockProductRepository)(nil).UpdateMigration), ctx, migration)
}

// MockOrderRepository is a mock of OrderRepository interface.
type MockOrderRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrderRepositoryMockRecorder
	isgomock struct{}
}

// MockOrderRepositoryMockRecorder is the mock recorder for MockOrderRepository.
type MockOrderRepositoryMockRecorder struct {
	mock *MockOrderRepository
}

// NewMockOrderRepository creates a new mock instance.
func NewMockOrderRepository(ctrl *gomock.Controller) *MockOrderRepository {
	mock := &MockOrderRepository{ctrl: ctrl}
	mock.recorder = &MockOrderRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderRepository) EXPECT() *MockOrderRepositoryMockRecorder {
	return m.recorder
}

// PlaceOrder mocks base method.
func (m *MockOrderRepository) PlaceOrder(ctx context.Context, order *models.Order) (*models.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlaceOrder", ctx, order)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlaceOrder indicates an expected call of PlaceOrder.
func (mr *MockOrderRepositoryMockRecorder) PlaceOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlaceOrder", reflect.TypeOf((*MockOrderRepository)(nil).PlaceOrder), ctx, order)
}

// MockCouponRepository is a mock of CouponRepository interface.
type MockCouponRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCouponRepositoryMockRecorder
	isgomock struct{}
}

// MockCouponRepositoryMockRecorder is the mock recorder for MockCouponRepository.
type MockCouponRepositoryMockRecorder struct {
	mock *MockCouponRepository
}

// NewMockCouponRepository creates a new mock instance.
func NewMockCouponRepository(ctrl *gomock.Controller) *MockCouponRepository {
	mock := &MockCouponRepository{ctrl: ctrl}
	mock.recorder = &MockCouponRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouponRepository) EXPECT() *MockCouponRepositoryMockRecorder {
	return m.recorder
}

// ValidateCouponCode mocks base method.
func (m *MockCouponRepository) ValidateCouponCode(ctx context.Context, couponCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCouponCode", ctx, couponCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateCouponCode indicates an expected call of ValidateCouponCode.
func (mr *MockCouponRepositoryMockRecorder) ValidateCouponCode(ctx, couponCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCouponCode", reflect.TypeOf((*MockCouponRepository)(nil).ValidateCouponCode), ctx, couponCode)
}
